const faqs = [
  "Why should I choose Aug AI for Generative AI development?",
  "How does Aug AI ensure the quality of the content generated by AI?",
  "What makes Aug AI's Generative AI solutions scalable?",
  "How does Aug AI fit Generative AI to my business?",
];

export default function Discover() {
  return (
    <section
      className="bg-white text-black"
      aria-labelledby="discover-faq-heading"
    >
      <div className="mx-auto w-full max-w-6xl px-4 pb-16 pt-16 text-center sm:px-6 sm:pb-20 sm:pt-20 lg:px-8 lg:pb-24 lg:pt-24">
        <h2
          id="discover-faq-heading"
          className="mx-auto max-w-4xl text-4xl font-bold leading-[1.22] tracking-tight text-black sm:text-5xl lg:max-w-5xl lg:text-6xl"
        >
          <span className="block">Your questions, answered</span>
          <span className="mt-3 block text-xl font-light lowercase leading-snug tracking-normal text-neutral-600 sm:mt-4 sm:text-2xl lg:text-3xl">
            discover everything you need to know!
          </span>
        </h2>

        <div className="mt-14 w-full sm:mt-16">
          <div className="mx-auto w-full max-w-[760px]">
            <div className="h-px w-full bg-neutral-200" aria-hidden />

            {faqs.map((q) => (
              <div key={q}>
                <div className="flex items-center justify-between gap-8 py-10">
                  <p className="min-w-0 flex-1 text-left text-lg font-medium leading-snug text-black sm:text-xl sm:leading-snug">
                    {q}
                  </p>
                  <div
                    className="flex h-12 w-12 shrink-0 items-center justify-center text-black/70"
                    aria-hidden
                  >
                    <span className="text-4xl font-extralight leading-none">+</span>
                  </div>
                </div>
                <div className="h-px w-full bg-neutral-200" aria-hidden />
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
