"use client";

import Image from "next/image";

import questionBanner from "../public/questionbanner.png";

const faqs = [
  "Why should I choose Aug AI for Generative AI development?",
  "How does Aug AI ensure the quality of the content generated by AI?",
  "What makes Aug AI's Generative AI solutions scalable?",
  "How does Aug AI fit Generative AI to my business?",
];

export default function ServicesQuestionsSection() {
  return (
    <section className="relative min-h-screen bg-black text-white" aria-labelledby="services-faq-heading">
      <div className="pointer-events-none absolute inset-0">
        <Image
          src={questionBanner}
          alt=""
          fill
          priority={false}
          sizes="100vw"
          className="object-cover object-center"
        />
      </div>
      <div className="absolute inset-0 bg-black/20" />

      <div className="relative z-10 mx-auto flex min-h-screen w-full max-w-6xl flex-col px-4 pb-16 pt-16 sm:px-6 sm:pb-20 sm:pt-20 lg:px-8 lg:pb-24 lg:pt-24">
        <h2
          id="services-faq-heading"
          className="mx-auto text-center text-4xl font-light leading-[1.22] tracking-tight sm:text-5xl lg:text-6xl lg:max-w-4xl"
        >
          Your questions, answered
          <br />
          <span className="mt-3 inline-block">discover everything you need to know!</span>
        </h2>

        <div className="mt-14 flex w-full justify-center sm:mt-16 lg:mt-18">
          <div className="w-full max-w-[920px] rounded-[1.75rem] border border-white/15 bg-white/10 px-6 py-3 shadow-[0_25px_70px_-45px_rgba(0,0,0,0.6)] backdrop-blur-xl sm:rounded-[2rem] sm:px-10 sm:py-5">
            {faqs.map((q, idx) => (
              <div key={q} className="relative">
                <div className="flex items-center justify-between gap-10 py-8 sm:py-9">
                  <p className="mx-auto max-w-[42rem] text-center text-base font-medium leading-relaxed text-white/90 sm:text-xl sm:leading-relaxed">
                    {q}
                  </p>
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center text-white/80">
                    <span className="text-4xl font-extralight leading-none">+</span>
                  </div>
                </div>

                <div aria-hidden="true" className="h-px w-full bg-white/20" />
                {idx === faqs.length - 1 ? null : <div aria-hidden="true" className="hidden" />}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
